import { Translations } from './types';

export const THEME_COLORS = {
  primary: '#0f766e', // Deep Teal (Professional)
  secondary: '#f59e0b', // Amber/Gold (Accent)
  background: '#f8fafc',
  surface: '#ffffff',
  text: '#1e293b',
};

export const TRANSLATIONS: Record<'en' | 'ar', Translations> = {
  en: {
    loginTitle: "Welcome Back",
    registerTitle: "Create Account",
    loginSubtitle: "Sign in to continue to your account",
    registerSubtitle: "Join us and start your journey",
    firstName: "First Name",
    lastName: "Last Name",
    email: "Email Address",
    phone: "Phone Number",
    password: "Password",
    confirmPassword: "Confirm Password",
    gender: "Gender",
    genderMale: "Male",
    genderFemale: "Female",
    nationality: "Nationality",
    rememberMe: "Remember me",
    forgotPassword: "Forgot Password?",
    loginBtn: "Login",
    registerBtn: "Register",
    haveAccount: "Already have an account?",
    noAccount: "Don't have an account?",
    switchToLogin: "Login here",
    switchToRegister: "Register here",
    language: "Language",
    required: "This field is required",
    invalidEmail: "Invalid email format",
    passwordsNoMatch: "Passwords do not match",
    successLogin: "Login successful!",
    successRegister: "Registration successful!",
    loading: "Processing...",
  },
  ar: {
    loginTitle: "مرحبًا بعودتك",
    registerTitle: "إنشاء حساب",
    loginSubtitle: "سجل الدخول للمتابعة إلى حسابك",
    registerSubtitle: "انضم إلينا وابدأ رحلتك",
    firstName: "الاسم الأول",
    lastName: "الاسم الأخير",
    email: "البريد الإلكتروني",
    phone: "رقم الهاتف",
    password: "كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    gender: "الجنس",
    genderMale: "ذكر",
    genderFemale: "أنثى",
    nationality: "الجنسية",
    rememberMe: "تذكرني",
    forgotPassword: "نسيت كلمة المرور؟",
    loginBtn: "تسجيل الدخول",
    registerBtn: "تسجيل",
    haveAccount: "لديك حساب بالفعل؟",
    noAccount: "ليس لديك حساب؟",
    switchToLogin: "سجل دخولك هنا",
    switchToRegister: "سجل هنا",
    language: "اللغة",
    required: "هذا الحقل مطلوب",
    invalidEmail: "صيغة البريد الإلكتروني غير صحيحة",
    passwordsNoMatch: "كلمات المرور غير متطابقة",
    successLogin: "تم تسجيل الدخول بنجاح!",
    successRegister: "تم التسجيل بنجاح!",
    loading: "جاري المعالجة...",
  },
};

export const COUNTRIES = [
  "Saudi Arabia",
  "United Arab Emirates",
  "Egypt",
  "Kuwait",
  "Qatar",
  "Bahrain",
  "Oman",
  "Jordan",
  "United States",
  "United Kingdom",
  "Other"
];
